name: Caller Workflow from trainee repository

on:
  push:
    branches:
      - main

jobs:
  # call-date:
  #   uses: shaik-byte/traineee/.github/workflows/reusable.yml@main


    
  call-addition:
    uses: shaik-byte/traineee/.github/workflows/reusable.yml@main
    with:
      number1: 100
      number2: 250
      # runner: ubuntu-latest
      
