name: Run Shell Script Every 1 Minute

on:
  schedule:
    - cron: '* * * * *'  # Every 1 minute
  

jobs:
  run-shell:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run shell script
        run: |
          echo "hi"
